### ISSUE TITLE
custom elf

### ISSUE THREAD

**Issue by NHSE** [aclich/PYNQ-Z2_Mask_Detection_Sreaming_system#3]
I made an elf file using Vitis AI. However, command 'make' using the elf file does not proceed due to formatting errors. Do you know how to solve this problem?

**Comment by aclich** [comment]
The caffe model is generated by vitis-ai v1.1, and the elf is compiled under DNNDK v3.1 with specific dcf file which generated by inputing custom XSA design file in "dlet" tool. You can find the XSA file [here](https://drive.google.com/file/d/1296fhViqp1naxSPvR30yYj0aSpSZ1kFk/view)
I'm sorry that I'm not able to provide an complete tutorial soon.

**Comment by NHSE** [comment]
Is it not possible to proceed with Vitisai v1.2?

**Comment by NHSE** [comment]
How should I write the target in the Json file? I'm sorry to bother you

**Comment by aclich** [comment]
> Is it not possible to proceed with Vitisai v1.2?

The Caffe model can be generated in Vitis-ai v1.2, but I'm not sure if the compilation of the elf file can be finished in Vitis-ai instead of DNNDK since Vitis-ai v1.2 appears not supporting the zynq-7000 series.



> How should I write the target in the Json file? I'm sorry to bother you

I think you can have a look in C++ json libs like [nlohmann/json](https://json.nlohmann.me/features/arbitrary_types/#basic-usage)
Or this [struct mapping](https://github.com/bk192077/struct_mapping) approachs to sotre your data in struct and save in json.

**Comment by aclich** [comment]
If you need DNNDKv3.1, you can refer to my another forked jobs [petalinux-docker](https://github.com/aclich/petalinux-docker/tree/add_DNNDK). It can help you build a docker image with petalinux and DNNDKv3.1.

**Comment by NHSE** [comment]
I sucessed the dcf file.
But I don't know how to compile with DNNDK_v3.1. Can you tell me?

**Comment by NHSE** [comment]
Can you tell me the tutorial?

**Comment by NHSE** [comment]
How do I create an elf file with DNNDK version 3.1?
I have to complete the execution of the custom YOLO by next Monday.
Can you help me?

**Comment by NHSE** [comment]
I succeeded Thank you!
